.TH PANDOC2RFC 1 "January 20, 2013" "Pandoc2rfc User Manual"
.SH NAME
.PP
pandoc2rfc - Process files with Pandoc syntax and run xml2rfc on them.
.SH SYNOPSIS
.PP
pandoc2rfc [\f[I]-THXNRh\f[]] [\f[I]FILE\f[]]...
.SH DESCRIPTION
.PP
Pandoc2rfc converts each file containing Pandoc syntax to a DOCBOOK XML
file.
When all files are converted, xml2rfc is called and a draft is created.
The intermediate XML files are removed afterwards.
.PP
The current directory must contain a file \f[C]template.xml\f[]
(otherwise use the \f[C]-t\f[] switch) which holds the "front" section
of the I-D you are building.
.PP
Currently there isn\[aq]t a standard extension for Pandoc source files,
so the following extension are recognized for the input files:
\f[C]\&.pdc\f[], \f[C]\&.pandoc\f[], \f[C]\&.mkd\f[],
\f[C]\&.markdown\f[], \f[C]\&.md\f[] and \f[C]\&.txt\f[]
.SH OPTIONS
.TP
.B -T
Output a draft.txt, a text version with page breaks.
This is the default.
.RS
.RE
.TP
.B -H
Output a draft.html.
.RS
.RE
.TP
.B -X
Output a draft.xml, with all references expanded.
.RS
.RE
.TP
.B -N
Output a draft.nroff.
.RS
.RE
.TP
.B -R
Output a draft.txt, a unpaginated text version.
.RS
.RE
.TP
.B -t TEMPLATE
Path to the template.xml, defaults to the current directory.
.RS
.RE
.TP
.B -x TRANSFORM
Path to the transform.xsl XSLT file, defaults to
/usr/lib/pandoc2rfc/transform.xsl.
.RS
.RE
.TP
.B -h
Show a short help message.
.RS
.RE
.SH SEE ALSO
.PP
\f[C]PANDOC\f[] (1) and the Pandoc documentation found at
<http://johnmacfarlane.net/pandoc/>.
.PP
See http://tools.ietf.org/html/draft-gieben-pandoc2rfc-00 for more
information on how to typeset an I-D.
.SH AUTHORS
Miek Gieben.
