.TH PANDOC2RFC 1 "January 20, 2013" "Pandoc2rfc User Manual"
.SH NAME
.PP
pandoc2rfc - Process files with Pandoc syntax and run xml2rfc on them.
.SH SYNOPSIS
.PP
pandoc2rfc [\f[I]-THXNRh\f[]] [\f[I]FILE\f[]]...
.SH DESCRIPTION
.PP
Pandoc2rfc converts each file containing Pandoc syntax to a DOCBOOK XML
file.
When all files are converted, xml2rfc is called and a draft is created.
The intermediate XML files are removed afterwards.
.SH OPTIONS
.TP
.B -T
Output a draft.txt, a text version with page breaks.
.RS
.RE
.TP
.B -H
Output a draft.html.
.RS
.RE
.TP
.B -X
Output a draft.xml, with all references expanded.
.RS
.RE
.TP
.B -N
Output a draft.nroff.
.RS
.RE
.TP
.B -R
Output a draft.txt, a unpaginated text version.
.RS
.RE
.TP
.B -t TEMPLATE
Give the path to the template.xml.
.RS
.RE
.TP
.B -h
Show a short help message.
.RS
.RE
.SH SEE ALSO
.PP
\f[C]PANDOC\f[] (1) and the Pandoc documentation found at
<http://johnmacfarlane.net/pandoc/>.
.SH AUTHORS
Miek Gieben.
