#!/usr/bin/perl

use warnings;
use strict;
use autodie;

if ( @ARGV > 0 and $ARGV[0] eq "-h" ) {
    print <<EOF;
Usage: single-xml [-h] [FILE]...
Iterate over the FILEs and read all <?rfc include=?> files recursively.
The ouput is one large XML file that can be used for the upload to the IETF.
Typical use in Pandoc2rfc: perl single-xml template.xml > draft.xml

Options:
  -h            this help
EOF
    exit;
}

sub include($);
if (@ARGV == 0) { $ARGV[0] = "/dev/stdin"; }
foreach (@ARGV) { include $_; }

sub include($) {
    open my $xml, "<", shift;
    while(<$xml>) {
        if ( /<\?rfc include=\"(.*)?\"\?>/ ) {
                include $1; next;
        }
        print;
    }
    close($xml);
}
