#!/usr/bin/perl

sub include($);

if ( @ARGV > 0 and $ARGV[0] eq "-h" ) {
    print <<EOF;
Usage: single-xml [-h] [FILE]...
Iterate over the FILEs and read all <?rfc included?> files recursively.
The ouput is one large XML file that can be used for the upload to the IETF.
Typical use in Pandoc2rfc: ./single template.xml > draft.xml

Options:
  -h            this help
EOF
    exit;
}

foreach (@ARGV) { include $_; }

sub include($) {
    local *XML;
    open XML, "<", shift or die "Can't open: $!\n";
    while(<XML>) {
        if ( /<\?rfc include=\"(.*)?\"\?>/ ) {
                include $1; next;
        }
        print;
    }
    close(XML);
}
